export const EDITOR_TEXT_COLOR_PRESETS = [
  { label: "기본", value: "" },
  { label: "검정", value: "#0f172a" },
  { label: "진한 회색", value: "#334155" },
  { label: "회색", value: "#64748b" },
  { label: "연한 회색", value: "#94a3b8" },
  { label: "흰색", value: "#ffffff" },
  { label: "빨강", value: "#dc2626" },
  { label: "주황", value: "#ea580c" },
  { label: "노랑", value: "#ca8a04" },
  { label: "초록", value: "#16a34a" },
  { label: "청록", value: "#0d9488" },
  { label: "파랑", value: "#2563eb" },
  { label: "남색", value: "#1d4ed8" },
  { label: "보라", value: "#7c3aed" },
  { label: "분홍", value: "#db2777" },
  { label: "갈색", value: "#a16207" },
] as const;

export const TABLE_CELL_BG_PRESETS = [
  { label: "없음", value: "" },
  { label: "흰색", value: "#ffffff" },
  { label: "연한 회색", value: "#f8fafc" },
  { label: "회색", value: "#e2e8f0" },
  { label: "진한 회색", value: "#94a3b8" },
  { label: "검정", value: "#0f172a" },
  { label: "연한 노랑", value: "#fef9c3" },
  { label: "노랑", value: "#fde047" },
  { label: "연한 주황", value: "#ffedd5" },
  { label: "주황", value: "#fdba74" },
  { label: "연한 초록", value: "#dcfce7" },
  { label: "초록", value: "#86efac" },
  { label: "연한 청록", value: "#ccfbf1" },
  { label: "연한 파랑", value: "#dbeafe" },
  { label: "파랑", value: "#93c5fd" },
  { label: "연한 보라", value: "#f3e8ff" },
  { label: "보라", value: "#d8b4fe" },
  { label: "연한 분홍", value: "#fce7f3" },
  { label: "분홍", value: "#f9a8d4" },
  { label: "연한 빨강", value: "#fee2e2" },
] as const;
